### ISSUE TITLE
Making sure chicken isn't on floor?

### ISSUE THREAD

**Issue by David-Rodden** [mxrcx/Epic-OSRS-Bot#1]
https://github.com/mxrcx/Epic-OSRS-Bot/blob/0d67edd86f6bfc74bf48d9ededeea7fa1a187b41/src/FightCow.java#L26

Seems like you're checking whether a chicken *doesn't* exist within exist within 50 paces of you. If you're fighting chicken, you might want to check instead if it does exist?

**Comment by mxrcx** [comment]
Raw chicken is the Loot of the chicken so I want to check if it is there and if it is not there then there has been no fight or there is still Loot laying around.
And can you tell me what 50 paces is? I just selected 50 because I couldn't find an explanation to the value.

**Comment by David-Rodden** [comment]
the game's movement system is grid-based, so if you click one tile away from your character, you're moving one pace in whichever direction you clicked. If you check for the distance of your pickable to be within a certain range: `nearest.distance() < 50`, this would mean your character's distance to that pickable would have to be fewer than 50 paces away.
