### ISSUE TITLE
Exclaiming your botting to others around you

### ISSUE THREAD

**Issue by David-Rodden** [mxrcx/Epic-OSRS-Bot#2]
https://github.com/mxrcx/Epic-OSRS-Bot/blob/0d67edd86f6bfc74bf48d9ededeea7fa1a187b41/src/FightCow.java#L38

I'd refrain from trying to tell others you're attacking the monster you've programmed to fight; otherwise, you're pretty much asking to be banned.

**Comment by mxrcx** [comment]
you are right that's a bit stupid :DD
